### ISSUE TITLE
[Question] Problems getting the user access token

### ISSUE THREAD

**Issue by B1ll1** [SammyK/LaravelFacebookSdk#140]
I'm having a problems trying to get the user access token, always null even if the user accepted my aplication. In my local aplication the package works fine but on my server I just cant get this user access token. Any ideia what it could be?

**Comment by vernard** [comment]
The reason for this is that according to the docs, the access token is saved on session with the key 'fb_user_access_token'.

You will have to manually add this access token to the `\SammyK\LaravelFacebookSdk\LaravelFacebookSdk` again on another request.

I'm working on a PR about this right now, because I've experienced the same problem.

**Comment by B1ll1** [comment]
My problem was the the server block of nginx, I had to add the configuration so it could accept parameters from facebook, basically it was bad configuration.

**Comment by vernard** [comment]
Oops! It seems my suggestion was off target. Glad you solved it.
