### ISSUE TITLE
How to use pagination?

### ISSUE THREAD

**Issue by d-a-n** [SammyK/LaravelFacebookSdk#71]
Are there any docs about those topics?

* Batch requests
* Easy pagination
* Getting Graph data returned as collections

Basically it's not clear how pagination works.

**Comment by Park66** [comment]
I'm looking for the same example you mentioned as well as how to use since/until/limit.

**Comment by SammyK** [comment]
@d-a-n All the docs are in the official Facebook PHP SDK's repo (but have yet to be published to the Facebook developer site).

- [Batch requests](https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/example_batch_request.fbmd)
- [Easy pagination](https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/example_pagination_basic.fbmd)
- [Getting Graph data returned as collections](https://github.com/facebook/facebook-php-sdk-v4/blob/master/docs/GraphNode.fbmd)

> as well as how to use since/until/limit.

@Park66 Those are just modifiers you send as params in the URL:

```php
$res = $fb->get('/me/photos?limit=1');
```

Not all endpoints support time-based modifiers like `since` & `until`. See the [full docs on pagination](https://developers.facebook.com/docs/graph-api/using-graph-api/v2.3#paging).

**Comment by DanDvoracek** [comment]
Hi there! 

I have a similar question. Is there a way to loop through the results list we get back from facebook? 

I'm trying to get more than 25 posts and my query doesn't seem to trigger the limit parameter of the url..

Here is what I do (should be enough for you to understand):
/?fields=picture{url},link,feed{message,name,object_id,from,permalink_url,created_time,full_picture,id,call_to_action,link,likes{name,username,id,pic}}&limit=50

I still get 25 posts and not 50.. Any idea why? Is it a facebook limitation? When I test it here https://developers.facebook.com/tools/explorer, it seems alright though.. Ideally I would like to get between 50 and 100 posts each time, as I have a cron job set up for that thing and I would like it to run every hour or more.

Any input would be welcome, thanks! And thank you @SammyK for that great plugin, it's very convenient!
